// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuscwdnfudsbzoqwxbgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1c2N3ZG5mdWRzYnpvcXd4YmdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwMDUwMTgsImV4cCI6MjA1MTU4MTAxOH0.nBpjMIQ2jnv7wvhey3h5Z7191HpSoQIjzARKxyDlnk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);